version: "3.8"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatsby
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true